=== MarginallyClever/Makelangelo-software/src/test/resources/translator/language_no_dup_key.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="language">        
        <xs:complexType>            
            <xs:sequence>
                <xs:element name="meta">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element type="xs:string" name="author"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="string" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="stringNotEmpty" name="key"/>
                            <xs:element type="stringNotEmpty" name="value"/>
                            <xs:element type="xs:string" name="hint" minOccurs="0"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" /> <!--default="EN" use="required" -->
                    </xs:complexType>
                   
                </xs:element>
            </xs:sequence>
            <xs:attribute name="lang" type="xs:string" default="EN"/> <!-- use="required" -->
        </xs:complexType>
        
        <xs:unique name="string_key_unique">
            <xs:selector xpath="string" />
            <xs:field xpath="key" />
        </xs:unique>
    </xs:element>
  
  
    <xs:simpleType name="stringNotEmpty">
        <xs:restriction base="xs:string">
            <xs:pattern value="(\n|.)+" />
            <!-- 
           error on CDATA with :
            <xs:pattern value=".+" />
             (as CDATA have been converted by the pre xml processor ? ther is non way to identifiy if or not a CDATA but )
           due to the fact that CDATA can containe \n
           <xs:pattern value="(\n|.)+" />
           or add
            <xs:whiteSpace value="collapse"/>            
            -->
        </xs:restriction>
    </xs:simpleType>
  
  
    <!--
    Restriction 
    https://www.w3schools.com/xml/schema_facets.asp
    
    
        <xs:whiteSpace value="preserve"/>
        vs
        <xs:whiteSpace value="replace"/>
        vs
        
        <xs:whiteSpace value="collapse"/>
    
    <xs:simpleType name="httpURI">
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="http://.*" />
        </xs:restriction>
    </xs:simpleType>
    -->
</xs:schema>

=== MarginallyClever/Makelangelo-software/src/test/resources/translator/english_with_dup_key.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language>
<language>
    <!-- To facilitate the validation and avoid duplicated key.
    please try to get language_no_dup_key.xsd from ...
        and change the beginig of the file with :
        
    <?xml version="1.0" encoding="UTF-8"?>
    <language xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="language_no_dup_key.xsd" >
        
-->
	<meta>
		<name>English</name>
		<author>Dan Royer (dan@marginallyclever.com)</author>
	</meta>

	<string>
		<key>BorderName</key>
		<value>Outline paper</value>
		<hint>Border generator</hint>
	</string>

	<string>
		<key>LissajousName</key>
		<value>Lissajous</value>
		<hint>Lissajous generator</hint>
	</string>
	<string>
		<key>KEY_A</key>
		<value>...</value>
                <hint></hint>
	</string>
	<string>
		<key>KEY_A</key>
		<value>...</value>
                <hint></hint>
	</string>
	<string>
		<key></key>
		<value>...</value>
		<hint></hint>
	</string>

	<string>
		<key>KEY_B</key>
		<value>...</value>
                <hint></hint>
	</string>
	<string>
		<key>KEY_B</key>
		<value>...</value>
                <hint></hint>
	</string>
</language>
